apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: agent-config-secret
  namespace: {{ .Values.namespace.name }}
data:
  K2_MAILBOX_ID: {{ .Values.secrets.K2_MAILBOX_ID | default "''" | b64enc }}
  K2_MANAGER_URL: {{ .Values.secrets.K2_MANAGER_URL | default "''" | b64enc }}
  kubeInterface: {{ .Values.secrets.kubeInterface | default "''" | b64enc }}
  kubeToken: {{ .Values.secrets.kubeToken | default "''" | b64enc }}
