{{- if .Values.image.repoSecret.enabled -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}
{{- end }}
